/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WriteupsRouteImport } from './routes/writeups'
import { Route as HobbiesRouteImport } from './routes/hobbies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WriteupsSlugRouteImport } from './routes/writeups.$slug'

const WriteupsRoute = WriteupsRouteImport.update({
  id: '/writeups',
  path: '/writeups',
  getParentRoute: () => rootRouteImport,
} as any)
const HobbiesRoute = HobbiesRouteImport.update({
  id: '/hobbies',
  path: '/hobbies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteupsSlugRoute = WriteupsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WriteupsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hobbies': typeof HobbiesRoute
  '/writeups': typeof WriteupsRouteWithChildren
  '/writeups/$slug': typeof WriteupsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hobbies': typeof HobbiesRoute
  '/writeups': typeof WriteupsRouteWithChildren
  '/writeups/$slug': typeof WriteupsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hobbies': typeof HobbiesRoute
  '/writeups': typeof WriteupsRouteWithChildren
  '/writeups/$slug': typeof WriteupsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/hobbies' | '/writeups' | '/writeups/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/hobbies' | '/writeups' | '/writeups/$slug'
  id: '__root__' | '/' | '/about' | '/hobbies' | '/writeups' | '/writeups/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HobbiesRoute: typeof HobbiesRoute
  WriteupsRoute: typeof WriteupsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writeups': {
      id: '/writeups'
      path: '/writeups'
      fullPath: '/writeups'
      preLoaderRoute: typeof WriteupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hobbies': {
      id: '/hobbies'
      path: '/hobbies'
      fullPath: '/hobbies'
      preLoaderRoute: typeof HobbiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writeups/$slug': {
      id: '/writeups/$slug'
      path: '/$slug'
      fullPath: '/writeups/$slug'
      preLoaderRoute: typeof WriteupsSlugRouteImport
      parentRoute: typeof WriteupsRoute
    }
  }
}

interface WriteupsRouteChildren {
  WriteupsSlugRoute: typeof WriteupsSlugRoute
}

const WriteupsRouteChildren: WriteupsRouteChildren = {
  WriteupsSlugRoute: WriteupsSlugRoute,
}

const WriteupsRouteWithChildren = WriteupsRoute._addFileChildren(
  WriteupsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HobbiesRoute: HobbiesRoute,
  WriteupsRoute: WriteupsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
